version: "3.9"
services:
  add_package:
    image: add_package
    build:
      context: .
      args:
        NODE_NAME: node
        PORT: 5555
        JAVA_HOME: /opt/softwareag/jvm/jvm
        PATH: $PATH:$JAVA_HOME/bin
      dockerfile: 
        -
          FROM sagcr.azurecr.io/webmethods-integrationserver:10.15
          COPY MyTestPackage /opt/softwareag/IntegrationServer/instances/default/package
          EXPOSE 5555 9999
          CMD ["/opt/softwareag/IntegrationServer/bin/server.sh", "start"]

