version: '3.9'
services:
  webmethods:
    image: sagcr.azurecr.io/webmethods-integrationserver:10.15
    environment:
      NODE_NAME: node
      PORT: 5555
      JAVA_HOME: /opt/softwareag/jvm/jvm
      PATH: $PATH:$JAVA_HOME/bin
    ports:
      - "5555:5555"
      - "9999:9999"
    volumes:
      - ./MyTestPackage:/opt/softwareag/IntegrationServer/instances/default/package
    command: [ "/opt/softwareag/IntegrationServer/bin/server.sh", "start"]
