version: "3.9"

services:
  flow-service:
    build:
      context: .
    image: my-flow-service
    ports:
      - "5555:5555"
      - "9999:9999"
    environment:
      - NODE_NAME=node
      - PORT=5555
    command: /opt/softwareag/profiles/IS_default/bin/startup.sh
