version: '3'
services:
  flow-serve-builder:
    build:
      context: .
      dockerfile: |
        FROM sagcr.azurecr.io/webmethods-integrationserver:10.15
        COPY MyTestPackage /opt/softwareag/IntegrationServer/instances/default/package
        EXPOSE 5555 9999
        CMD ["/opt/softwareag/IntegrationServer/bin/server.sh", "start"]
    image: flow-serve

  flow-serve-runner:
    image: flow-serve
    environment:
      NODE_NAME: node
      PORT: 5555
      JAVA_HOME: /opt/softwareag/jvm/jvm
      PATH: $PATH:$JAVA_HOME/bin
    ports:
      - "5555:5555"
      - "9999:9999"
